# fly.toml app configuration file generated for sakamico on 2024-03-14T11:27:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sakamico'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/resources/healthcheck'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
